//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Taller.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MiServicioSoap")]
    public interface MiServicioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Tabla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Consulta_Tabla();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Tabla", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Consulta_TablaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Consulta_Id(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Id", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Consulta_IdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Marca", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Consulta_Marca(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Marca", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Consulta_MarcaAsync(string marca);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MiServicioSoapChannel : Proyecto_Taller.ServiceReference1.MiServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioSoapClient : System.ServiceModel.ClientBase<Proyecto_Taller.ServiceReference1.MiServicioSoap>, Proyecto_Taller.ServiceReference1.MiServicioSoap {
        
        public MiServicioSoapClient() {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Consulta_Tabla() {
            return base.Channel.Consulta_Tabla();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Consulta_TablaAsync() {
            return base.Channel.Consulta_TablaAsync();
        }
        
        public System.Data.DataSet Consulta_Id(int id) {
            return base.Channel.Consulta_Id(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Consulta_IdAsync(int id) {
            return base.Channel.Consulta_IdAsync(id);
        }
        
        public System.Data.DataSet Consulta_Marca(string marca) {
            return base.Channel.Consulta_Marca(marca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Consulta_MarcaAsync(string marca) {
            return base.Channel.Consulta_MarcaAsync(marca);
        }
    }
}
